#!/usr/bin/env bash

source $HOME/.rvm/scripts/rvm

cd $HOME/current/

rvm gemset import rvm-site.gems

nanoc3 co --verbose

rsync -avgz content/assets/images/ public/images/
rsync -avgz content/assets/pdf/ public/pdf/

