#!/usr/bin/env bash

enter "$stage_path"

source_files "$HOME/.rvm/scripts/rvm"

if command_exists rvm
then
  rvm gemset import rvm-site.gems
fi

if command_exists nanoc3
then
  nanoc3 co --verbose
fi

# TODO: Enable to specify copy_paths and symlink_paths for deploys.
if directory_exists "content/assets/images"
then
  rsync -avgz content/assets/images/ public/images/
fi

if directory_exists "content/assets/pdf"
then
  rsync -avgz content/assets/pdf/ public/pdf/
fi

